# syntax=docker/dockerfile:1.7

ARG PYTHON_VERSION=3.12

FROM registry.access.redhat.com/ubi9/ubi-minimal:9.5@sha256:a50731d3397a4ee28583f1699842183d4d24fadcc565c4688487af9ee4e13a44

ARG PYTHON_VERSION

LABEL org.opencontainers.image.title="python-ubi9"
LABEL org.opencontainers.image.description="Python ${PYTHON_VERSION} on UBI9 minimal"
LABEL org.opencontainers.image.source="https://github.com/nq-rdl/container-images"
LABEL org.opencontainers.image.vendor="Research Data Laboratory"
LABEL org.opencontainers.image.licenses="MIT"

RUN microdnf install -y --nodocs \
        python${PYTHON_VERSION} \
        python${PYTHON_VERSION}-pip \
        shadow-utils \
        ca-certificates \
        glibc-langpack-en \
    && microdnf clean all \
    && rm -rf /var/cache/yum /var/cache/dnf

RUN ln -sf python${PYTHON_VERSION} /usr/bin/python3 \
    && ln -sf python3 /usr/bin/python \
    && ln -sf pip${PYTHON_VERSION} /usr/bin/pip3 \
    && ln -sf pip3 /usr/bin/pip

ENV LANG=en_US.UTF-8 \
    PYTHONDONTWRITEBYTECODE=1 \
    PYTHONUNBUFFERED=1 \
    PIP_NO_CACHE_DIR=1

RUN useradd -u 1001 -g 0 -m -d /home/app -s /sbin/nologin app
USER 1001
WORKDIR /home/app

ENTRYPOINT ["python3"]
CMD ["--help"]
