version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: monday
    groups:
      actions:
        patterns: ["*"]
    commit-message:
      prefix: "ci"

  - package-ecosystem: docker
    directory: /images/bun-ubi9
    schedule:
      interval: weekly
    commit-message:
      prefix: "image(bun-ubi9)"

  - package-ecosystem: docker
    directory: /images/spark-ubi9
    schedule:
      interval: weekly
    commit-message:
      prefix: "image(spark-ubi9)"

  - package-ecosystem: docker
    directory: /images/pyspark-ubi9
    schedule:
      interval: weekly
    commit-message:
      prefix: "image(pyspark-ubi9)"

  - package-ecosystem: docker
    directory: /images/spark-operator-ubi9
    schedule:
      interval: weekly
    commit-message:
      prefix: "image(spark-operator-ubi9)"
