version: 2
updates:
  - package-ecosystem: docker
    directory: /images/pixi-ubi9
    schedule:
      interval: weekly
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: monday
    groups:
      actions:
        patterns: ["*"]
    commit-message:
      prefix: "ci"
