name: Triage

permissions:
  contents: read
  packages: read

on:
  issues:
    types: [opened]
  pull_request_target:
    types: [opened, ready_for_review]

jobs:
  triage:
    uses: nq-rdl/.github/.github/workflows/auto-triage.yml@d9e70f7d2866e2c126660b924e4e5421e8dbaaba
    with:
      domain: Infrastructure
      lead: rowdenbr
    secrets: inherit
