name: Triage

permissions:
  contents: read
  packages: read

on:
  issues:
    types: [opened]
  pull_request_target:
    types: [opened, ready_for_review]

jobs:
  triage:
    if: github.event_name == 'issues' || github.event.pull_request.head.repo.full_name == github.repository
    uses: nq-rdl/.github/.github/workflows/auto-triage.yml@7165568a22c4eb823a6424593d921edd0f30a29d
    with:
      domain: Infrastructure
    secrets: inherit
